### ISSUE TITLE
rollup uses browser version of module

### ISSUE THREAD

**Issue by nickjevershed** [guardian/interactive-atom-template#4]
With the previous es6 interactive template it was possible to import everything in a module, eg

import * as d3 from "d3";
var selection = d3.select("thing");

worked fine. 

In this interactive atom template, the above gives the error: 

src/js/app.js (3:16) 'select' is not exported by 'node_modules/d3/build/d3.js'

when building.

**Comment by nickjevershed** [comment]
This seems to be due to the browser argument in 'rollup-plugin-node-resolve' being set to true. setting it to false fixes the issue. What's the reason for setting browser: true ?

**Comment by thiagodebastos** [comment]
@nickjevershed There's a quick explanation here:
https://github.com/rollup/rollup-plugin-node-resolve

> some package.json files have a `browser` field which
specifies alternative files to load for people bundling
for the browser. If that's you, use this option, otherwise
pkg.browser will be ignored
browser: true,  // Default: false

Maybe there is some package the UK guys use regularly that depend on this setting. Otherwise I'm not sure why this would be set to true.

**Comment by tinius** [comment]
@nickjevershed @thiagodebastos Hi from the London offices. I'm not aware of a specific package where this setting has made a difference, but it certainly seems sensible to use the `browser` entry point where it exists, as that's exactly where the relevant code will be running.

As for D3 and similar libraries, unfortunately we haven't yet found an idiomatic way to solve this. Two hacky workarounds I'm aware of are:

```
import * as d3 from 'd3/index'
```

```
import * as blah from 'd3'
const d3 = blah.__moduleExports
```

**Comment by thiagodebastos** [comment]
Thanks @tinius, I haven't run across this issue myself yet, but I will be using D3 in very soon and will refer back to this hacky solution, cheers!

**Comment by nickjevershed** [comment]
No longer an issue!
